//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPOModHelperArchiver.I18n {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REPOModHelperArchiver.I18n.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 构建.
        /// </summary>
        internal static string FormBuild_FormBuildTitle {
            get {
                return ResourceManager.GetString("FormBuild/FormBuildTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 停止构建.
        /// </summary>
        internal static string FormBuild_StopBuild {
            get {
                return ResourceManager.GetString("FormBuild/StopBuild", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 开始打包.
        /// </summary>
        internal static string FormMain_BtnStartText {
            get {
                return ResourceManager.GetString("FormMain/BtnStartText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 创建安装包成功！.
        /// </summary>
        internal static string FormMain_CreateArchiveSuccess {
            get {
                return ResourceManager.GetString("FormMain/CreateArchiveSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 基础MOD作者网址：.
        /// </summary>
        internal static string FormMain_CustomAuthorURL {
            get {
                return ResourceManager.GetString("FormMain/CustomAuthorURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自定义基础MOD文件夹.
        /// </summary>
        internal static string FormMain_CustomBase {
            get {
                return ResourceManager.GetString("FormMain/CustomBase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 基础MOD名称：.
        /// </summary>
        internal static string FormMain_CustomBaseName {
            get {
                return ResourceManager.GetString("FormMain/CustomBaseName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自定义基础MOD名称包含特殊字符！.
        /// </summary>
        internal static string FormMain_CustomBaseNameNotValid {
            get {
                return ResourceManager.GetString("FormMain/CustomBaseNameNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 基础MOD文件夹：.
        /// </summary>
        internal static string FormMain_CustomBasePath {
            get {
                return ResourceManager.GetString("FormMain/CustomBasePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自定义基础MOD文件夹不存在！请确认选择的文件夹包含 BepInEx 子目录！.
        /// </summary>
        internal static string FormMain_CustomBasePathNotExists {
            get {
                return ResourceManager.GetString("FormMain/CustomBasePathNotExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 可选MOD文件夹：.
        /// </summary>
        internal static string FormMain_CustomOptionalPath {
            get {
                return ResourceManager.GetString("FormMain/CustomOptionalPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 可选MOD文件夹不存在！.
        /// </summary>
        internal static string FormMain_CustomOptionalPathNotExists {
            get {
                return ResourceManager.GetString("FormMain/CustomOptionalPathNotExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 基础MOD描述文案：.
        /// </summary>
        internal static string FormMain_CustomREADME {
            get {
                return ResourceManager.GetString("FormMain/CustomREADME", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 基础MOD更新网址：.
        /// </summary>
        internal static string FormMain_CustomUpdateURL {
            get {
                return ResourceManager.GetString("FormMain/CustomUpdateURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string FormMain_Error {
            get {
                return ResourceManager.GetString("FormMain/Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 致命公司安装器打包程序.
        /// </summary>
        internal static string FormMain_FormMainTitle {
            get {
                return ResourceManager.GetString("FormMain/FormMainTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 缺少安装器文件：.
        /// </summary>
        internal static string FormMain_InstallerFileMissing {
            get {
                return ResourceManager.GetString("FormMain/InstallerFileMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请选择自定义基础MOD文件夹.
        /// </summary>
        internal static string FormMain_SelectCustomBaseFolder {
            get {
                return ResourceManager.GetString("FormMain/SelectCustomBaseFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请选择自定义可选MOD文件夹.
        /// </summary>
        internal static string FormMain_SelectCustomOptionalFolder {
            get {
                return ResourceManager.GetString("FormMain/SelectCustomOptionalFolder", resourceCulture);
            }
        }
    }
}
